import { createFileRoute, Link } from "@tanstack/react-router";

export const Route = createFileRoute("/terms")({
  head: () => ({
    meta: [
      { title: "Terms & Conditions — Scanything" },
      {
        name: "description",
        content: "Terms and conditions for using Scanything.",
      },
      { property: "og:title", content: "Terms & Conditions — Scanything" },
      {
        property: "og:description",
        content: "Terms and conditions for using Scanything.",
      },
      { property: "og:type", content: "website" },
      { name: "twitter:card", content: "summary" },
    ],
  }),
  component: TermsPage,
});

const SELLER_NAME = "John FREDRIK Mikael Paulsson";
const APP_NAME = "Scanything";
const CONTACT_EMAIL = "scanythingapp@gmail.com";

function TermsPage() {
  return (
    <div className="min-h-screen bg-background text-foreground">
      <header className="sticky top-0 z-20 border-b border-border/60 bg-background/70 backdrop-blur">
        <div className="mx-auto flex max-w-3xl items-center justify-between gap-2 px-4 py-3">
          <Link to="/" className="text-sm font-medium text-primary hover:underline">
            ← Back to Scanything
          </Link>
          <span className="text-xs text-muted-foreground">Terms & Conditions</span>
        </div>
      </header>

      <main className="mx-auto max-w-3xl px-4 py-8">
        <h1 className="mb-2 text-3xl font-bold gold-text">Terms & Conditions</h1>
        <p className="mb-8 text-sm text-muted-foreground">Last updated: {new Date().toLocaleDateString()}</p>

        <div className="space-y-6 text-sm leading-relaxed text-muted-foreground">
          <section>
            <h2 className="mb-2 text-lg font-semibold text-foreground">1. Seller information</h2>
            <p>
              These Terms & Conditions are between you and <strong className="text-foreground">{SELLER_NAME}</strong>, the seller of {APP_NAME}. By using the app, you agree to these terms. If you do not agree, please do not use {APP_NAME}.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-lg font-semibold text-foreground">2. Product description</h2>
            <p>
              {APP_NAME} is a camera-based AI tool that identifies objects, text, signs, and people in photos and live video. It provides approximate information such as names, categories, estimated price ranges, and links to third-party search results. Outputs are generated by AI and should be treated as suggestions, not definitive facts.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-lg font-semibold text-foreground">3. Acceptance of terms</h2>
            <p>
              By accessing or using {APP_NAME}, you confirm that you are at least 18 years old or have the authority to accept these terms on behalf of your organization. Continued use of the app means you accept any future updates to these terms.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-lg font-semibold text-foreground">4. Acceptable use</h2>
            <p>You agree not to use {APP_NAME} to:</p>
            <ul className="mt-2 list-disc space-y-1 pl-5">
              <li>violate any applicable law or regulation;</li>
              <li>infringe intellectual property, privacy, or other rights of others;</li>
              <li>send spam, malware, or abusive content;</li>
              <li>interfere with the security or availability of the service;</li>
              <li>scrape, reverse-engineer, or attempt to extract the app's source code;</li>
              <li>use the app to identify or harass individuals without consent.</li>
            </ul>
          </section>

          <section>
            <h2 className="mb-2 text-lg font-semibold text-foreground">5. Accounts and credentials</h2>
            <p>
              You may create an account to save your credit balance and purchase history. You are responsible for keeping your login credentials secure and for all activity under your account. Please provide accurate information and keep it updated.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-lg font-semibold text-foreground">6. Payments and credits</h2>
            <p>
              {APP_NAME} uses Paddle.com as the Merchant of Record for all payments. This means Paddle processes payments, taxes, billing, subscriptions, cancellations, and refunds on behalf of {SELLER_NAME}. All payment terms are governed by{" "}
              <a
                href="https://www.paddle.com/legal/checkout-buyer-terms"
                target="_blank"
                rel="noopener noreferrer"
                className="text-primary underline"
              >
                Paddle's Buyer Terms
              </a>
              . Credits purchased are non-refundable except as described in our Refund Policy.
            </p>
            <p className="mt-2">
              Our order process is conducted by our online reseller Paddle.com. Paddle.com is the Merchant of Record for all our orders. Paddle provides all customer service inquiries and handles returns.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-lg font-semibold text-foreground">7. Intellectual property</h2>
            <p>
              {SELLER_NAME} owns all rights to the {APP_NAME} software, branding, and content, except for user-generated content and third-party links. You are granted a limited, non-exclusive, non-transferable license to use the app for personal or internal business purposes within your account.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-lg font-semibold text-foreground">8. User content</h2>
            <p>
              Images and inputs you upload are processed to provide the service. You retain ownership of your content. You grant {SELLER_NAME} a limited license to process your content solely to operate the app.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-lg font-semibold text-foreground">9. Service level and disclaimers</h2>
            <p>
              {APP_NAME} is provided "as is". We do not guarantee that the service will be uninterrupted, error-free, or that AI outputs will always be accurate. You are responsible for how you use the information provided by the app.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-lg font-semibold text-foreground">10. Suspension and termination</h2>
            <p>
              We may suspend or terminate your access if you materially breach these terms, engage in fraud or abuse, or create a security risk. You may stop using the app at any time.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-lg font-semibold text-foreground">11. Liability</h2>
            <p>
              To the fullest extent permitted by law, {SELLER_NAME}'s liability is limited to the amount you paid for the service in the 12 months before the claim. We are not liable for indirect, consequential, or special damages such as lost profits or data loss, except where required by law (e.g. fraud, death, or personal injury).
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-lg font-semibold text-foreground">12. Indemnity</h2>
            <p>
              You agree to indemnify {SELLER_NAME} for claims arising from your content, unlawful use, or violation of these terms.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-lg font-semibold text-foreground">13. Governing law and disputes</h2>
            <p>
              These terms are governed by the laws of Sweden. Any dispute shall be resolved in the courts of Sweden.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-lg font-semibold text-foreground">14. Changes to these terms</h2>
            <p>
              We may update these terms from time to time. The latest version will always be available at this page. If you continue to use {APP_NAME} after changes, you accept the updated terms.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-lg font-semibold text-foreground">15. Contact</h2>
            <p>
              For questions about these terms, contact us at{" "}
              <a href={`mailto:${CONTACT_EMAIL}`} className="text-primary underline">
                {CONTACT_EMAIL}
              </a>
              .
            </p>
          </section>
        </div>
      </main>
    </div>
  );
}
